### ISSUE TITLE
Nuke submodules

### ISSUE THREAD

**Issue by bmann** [idno/S3#3]
I'm trying to use this on Heroku and the submodules with submodules is a pain in the ass.

Having a top level composer.json file that autoloaded the dependencies would be much cleaner. I'm a bit in the dark about this, got composer to grab all the submodule / dependencies, but don't know how to hack and slash the Main.php file to load them.

**Comment by benwerd** [comment]
We've nuked submodules everywhere else and will do so here too. Thanks for
the nudge!
